apiVersion: v1
kind: Service
metadata:
  name: bike-finder
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: bike-finder
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bike-finder
  labels:
    app: bike-finder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bike-finder
  template:
    metadata:
      labels:
        app: bike-finder
    spec:
      containers:
      - name: bike-finder
        image: crick120/bike-finder:v1
        ports:
        - containerPort: 8080
